name: check

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run tsc
      - run: npm run lint
      - run: npm run test
      - run: npm run build
      - run: npm run size

  e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps # chromium
      - name: Smoke test stories
        run: npm run storybook:test
      - name: Run Playwright tests
        run: npm run e2e
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
